### ISSUE TITLE
Stepping into the same exe again after relaunching raddbg re-opens files in the code view

### ISSUE THREAD

**Issue by rjurga** [EpicGamesExt/raddebugger#346]
I have a project where I usually debug a given exe.

If I have my main file open in raddbg, I can step into it just fine. Then, if I close and relaunch raddbg, and I try to step into the main file again (by using F10) it opens the main file again in a new tab.

Here is a screenshot with the main file open in several tabs after restarting the debugger and stepping multiple times:
![image](https://github.com/user-attachments/assets/f50bf1f5-bff8-432d-b78b-129831447cf3)

There are some `<C:><..>` prefixes that I don't know the meaning of.

My file path map is empty, if it matters.

My project directories look like this:
```
Wolves-jai
  Wolves.raddbg_project
  src
     main.jai
  output
    debug
      FermiSignal.exe
```
and I run raddbg by doing `start raddbg --project:Wolves.raddbg_project` in the `Wolves-jai` directory.

Here's a copy of the `raddbg_project` file:
```
// raddbg project file

/// breakpoints ///////////////////////////////////////////////////////////////

breakpoint:
{
  location: ("../../../../../../../../../../../Projects/Wolves-jai/src/main.jai":22)
}

breakpoint:
{
  location: ("../../../../../Projects/Wolves-jai/src/main.jai":25)
}

breakpoint:
{
  location: ("src/main.jai":25)
}

/// targets ///////////////////////////////////////////////////////////////////

target:
{
  name: "debug"
  executable: "output/debug/FermiSignal.exe"
  working_directory: "output/debug"
}

/// recent_files //////////////////////////////////////////////////////////////

recent_file:
{
  name: "../Wolves-jai"
  recent_file:
  {
    name: "../Wolves-jai"
    recent_file:
    {
      name: "../Wolves-jai"
      recent_file: "src/input.jai"
    }
  }
}

recent_file: "src/Wolves/renderer.jai"
recent_file: "src/Wolves/module.jai"
recent_file: "src/Wolves/input.jai"
recent_file: "src/raw_input.jai"
recent_file: "src/window.jai"
recent_file: "src/modules/runtime_support.jai"
recent_file: "src/modules/d3d11_layer.jai"
recent_file: "src/main.jai"

/// exception code filters ////////////////////////////////////////////////////

exception_code_filters:
{
  win32_ctrl_c: 1
  win32_ctrl_break: 1
  win32_win_rt_originate_error: 0
  win32_win_rt_transform_error: 0
  win32_rpc_call_cancelled: 0
  win32_datatype_misalignment: 0
  win32_access_violation: 1
  win32_in_page_error: 0
  win32_invalid_handle: 1
  win32_not_enough_quota: 0
  win32_illegal_instruction: 0
  win32_cannot_continue_exception: 0
  win32_invalid_exception_disposition: 0
  win32_array_bounds_exceeded: 0
  win32_floating_point_denormal_operand: 0
  win32_floating_point_division_by_zero: 0
  win32_floating_point_inexact_result: 0
  win32_floating_point_invalid_operation: 0
  win32_floating_point_overflow: 0
  win32_floating_point_stack_check: 0
  win32_floating_point_underflow: 0
  win32_integer_division_by_zero: 0
  win32_integer_overflow: 0
  win32_privileged_instruction: 0
  win32_stack_overflow: 0
  win32_unable_to_locate_dll: 0
  win32_ordinal_not_found: 0
  win32_entry_point_not_found: 0
  win32_dll_initialization_failed: 0
  win32_floating_point_sse_multiple_faults: 0
  win32_floating_point_sse_multiple_traps: 0
  win32_assertion_failed: 1
  win32_module_not_found: 0
  win32_procedure_not_found: 0
  win32_sanitizer_error_detected: 1
  win32_sanitizer_raw_access_violation: 0
  win32_directx_debug_layer: 1
}
```
